/**
 * ClarifyingQuestions Component
 *
 * Optional step before research to gather context.
 * Shows 2-4 questions generated by Haiku to refine the query.
 * User can answer or skip to proceed directly to research.
 *
 * @module components/ClarifyingQuestions
 */

'use client'

import { ChalkChat, ChalkArrowRight, ChalkLoading, ChalkChevronDown, ChalkChevronRight } from './ChalkIcons'
import { useState } from 'react'

interface ClarifyingQuestionsProps {
  /** Questions to display */
  questions: string[]
  /** Current answers (one per question) */
  answers: string[]
  /** Update answers array */
  onAnswerChange: (index: number, value: string) => void
  /** Submit with answers */
  onSubmit: (e: React.FormEvent) => void
  /** Skip questions and proceed directly */
  onSkip: () => void
  /** Whether form is disabled (loading) */
  isLoading: boolean
  /** Current session prompt (null = using default) */
  sessionPrompt: string | null
  /** Default prompt from settings */
  defaultPrompt: string
  /** Update session prompt */
  onSessionPromptChange: (value: string | null) => void
  /** Save current prompt as default */
  onSavePromptAsDefault: (value: string) => void
}

/**
 * Clarifying questions form.
 *
 * @example
 * <ClarifyingQuestions
 *   questions={clarifyingQuestions}
 *   answers={answers}
 *   onAnswerChange={(i, v) => updateAnswer(i, v)}
 *   onSubmit={handleAnswersSubmit}
 *   onSkip={() => runFullResearch(originalQuery)}
 *   isLoading={isLoading}
 * />
 */
export function ClarifyingQuestions({
  questions,
  answers,
  onAnswerChange,
  onSubmit,
  onSkip,
  isLoading,
  sessionPrompt,
  defaultPrompt,
  onSessionPromptChange,
  onSavePromptAsDefault,
}: ClarifyingQuestionsProps) {
  const [promptExpanded, setPromptExpanded] = useState(false)

  return (
    <form onSubmit={onSubmit}>
      <div className="bg-paper-card rounded-xl border border-paper-accent/30 overflow-hidden chalk-frame">
        {/* Header */}
        <div className="p-3 bg-paper-surface/30 border-b border-paper-accent/20">
          <p className="text-sm text-paper-text flex items-center gap-2">
            <ChalkChat size={16} className="text-paper-accent" />
            Quick context for better results (optional)
          </p>
        </div>

        {/* Questions */}
        <div className="p-4 space-y-3">
          {questions.map((question, i) => (
            <div key={i}>
              <label className="block text-sm font-medium text-paper-text mb-1">
                {i + 1}. {question}
              </label>
              <input
                type="text"
                value={answers[i] || ''}
                onChange={(e) => onAnswerChange(i, e.target.value)}
                placeholder="Optional"
                className="w-full px-3 py-2 border border-paper-accent/30 rounded-lg text-sm bg-paper-bg text-paper-text placeholder:text-paper-muted"
              />
            </div>
          ))}

          {/* Customize Summary Prompt (styled like a question) */}
          <div>
            <button
              type="button"
              onClick={() => setPromptExpanded(!promptExpanded)}
              className="block text-sm font-medium text-paper-text mb-1 text-left w-full hover:text-paper-accent transition-colors"
            >
              <span className="inline-flex items-center gap-1.5">
                {promptExpanded ? <ChalkChevronDown size={14} /> : <ChalkChevronRight size={14} />}
                {questions.length + 1}. Any specific instructions for the summary?
              </span>
            </button>

            {promptExpanded ? (
              <div className="space-y-2">
                <textarea
                  value={sessionPrompt ?? defaultPrompt}
                  onChange={(e) => onSessionPromptChange(e.target.value)}
                  rows={5}
                  className="w-full px-3 py-2 text-xs border border-paper-accent/30 rounded-lg bg-paper-bg text-paper-text font-mono resize-y placeholder:text-paper-muted"
                  placeholder="Customize how the summary is generated..."
                />
                <div className="flex items-center justify-between">
                  <span className="text-[10px] text-paper-muted">
                    This session only
                  </span>
                  <div className="flex items-center gap-3">
                    {sessionPrompt !== null && (
                      <button
                        type="button"
                        onClick={() => {
                          onSavePromptAsDefault(sessionPrompt ?? defaultPrompt)
                          onSessionPromptChange(null)
                        }}
                        className="text-[10px] text-paper-accent hover:underline"
                      >
                        Save as default
                      </button>
                    )}
                    {sessionPrompt !== null && (
                      <button
                        type="button"
                        onClick={() => onSessionPromptChange(null)}
                        className="text-[10px] text-paper-muted hover:text-paper-text"
                      >
                        Reset
                      </button>
                    )}
                  </div>
                </div>
              </div>
            ) : (
              <input
                type="text"
                readOnly
                onClick={() => setPromptExpanded(true)}
                placeholder={sessionPrompt !== null ? "Yes, customized" : "No, use default"}
                className="w-full px-3 py-2 border border-paper-accent/30 rounded-lg text-sm bg-paper-bg text-paper-muted placeholder:text-paper-muted cursor-pointer hover:border-paper-accent/50"
              />
            )}
          </div>
        </div>

        {/* Footer */}
        <div className="border-t border-paper-divider p-3 bg-paper-bg flex justify-between">
          <button
            type="button"
            onClick={onSkip}
            className="text-sm text-paper-muted hover:text-paper-text flex items-center gap-1"
          >
            Skip <ChalkArrowRight size={14} />
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-5 py-2 bg-paper-accent text-paper-bg rounded-lg text-sm font-medium disabled:opacity-50 inline-flex items-center gap-1.5"
          >
            {isLoading ? (
              <>
                <ChalkLoading size={14} /> Working...
              </>
            ) : (
              'Research'
            )}
          </button>
        </div>
      </div>
    </form>
  )
}
