/**
 * ClarifyingQuestions Component
 *
 * Optional step before research to gather context.
 * Shows 2-4 questions generated by Haiku to refine the query.
 * User can answer or skip to proceed directly to research.
 *
 * @module components/ClarifyingQuestions
 */

'use client'

interface ClarifyingQuestionsProps {
  /** Questions to display */
  questions: string[]
  /** Current answers (one per question) */
  answers: string[]
  /** Update answers array */
  onAnswerChange: (index: number, value: string) => void
  /** Submit with answers */
  onSubmit: (e: React.FormEvent) => void
  /** Skip questions and proceed directly */
  onSkip: () => void
  /** Whether form is disabled (loading) */
  isLoading: boolean
}

/**
 * Clarifying questions form.
 *
 * @example
 * <ClarifyingQuestions
 *   questions={clarifyingQuestions}
 *   answers={answers}
 *   onAnswerChange={(i, v) => updateAnswer(i, v)}
 *   onSubmit={handleAnswersSubmit}
 *   onSkip={() => runFullResearch(originalQuery)}
 *   isLoading={isLoading}
 * />
 */
export function ClarifyingQuestions({
  questions,
  answers,
  onAnswerChange,
  onSubmit,
  onSkip,
  isLoading,
}: ClarifyingQuestionsProps) {
  return (
    <form onSubmit={onSubmit}>
      <div className="bg-white dark:bg-slate-800 rounded-xl shadow-sm border border-slate-200 dark:border-slate-700 overflow-hidden">
        {/* Header */}
        <div className="p-3 bg-blue-50 dark:bg-blue-900/20 border-b border-blue-100 dark:border-blue-800">
          <p className="text-sm text-blue-700 dark:text-blue-300">
            💬 Quick context for better results (optional)
          </p>
        </div>

        {/* Questions */}
        <div className="p-4 space-y-3">
          {questions.map((question, i) => (
            <div key={i}>
              <label className="block text-sm font-medium text-slate-700 dark:text-slate-200 mb-1">
                {i + 1}. {question}
              </label>
              <input
                type="text"
                value={answers[i] || ''}
                onChange={(e) => onAnswerChange(i, e.target.value)}
                placeholder="Optional"
                className="w-full px-3 py-2 border border-slate-200 dark:border-slate-600 rounded-lg text-sm bg-white dark:bg-slate-900 dark:text-slate-100"
              />
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="border-t border-slate-100 dark:border-slate-700 p-3 bg-slate-50 dark:bg-slate-900 flex justify-between">
          <button
            type="button"
            onClick={onSkip}
            className="text-sm text-slate-500 dark:text-slate-400 hover:text-slate-700"
          >
            Skip →
          </button>
          <button
            type="submit"
            disabled={isLoading}
            className="px-5 py-2 bg-blue-600 dark:bg-blue-500 text-white rounded-lg text-sm font-medium disabled:opacity-50"
          >
            {isLoading ? '⏳' : 'Research'}
          </button>
        </div>
      </div>
    </form>
  )
}
